#!/bin/zsh
cd /Users/seif/Downloads/SAA-Study
CHAPTERS=(AdditionalServices Compute Containers ContentDeliveryDNS CostOptimization DatabasesNoSQL DatabasesRelational Decoupling HighAvailability MonitoringAudit Networking SecurityIdentity Serverless Storage)

check() {
  label="$1"
  pat="$2"
  hits=""
  for c in $CHAPTERS; do
    if grep -qiE "$pat" "$c.md" 2>/dev/null; then
      hits="$hits $c"
    fi
  done
  [ -z "$hits" ] && hits=" *** GAP — NONE ***"
  printf "%-24s ->%s\n" "$label" "$hits"
}

echo "=== COMPUTE / SERVERLESS / CONTAINERS ==="
check "Lambda" "lambda"
check "Fargate" "fargate"
check "ECS" "elastic container service|[^a-z]ecs[^a-z]"
check "EKS" "kubernetes|[^a-z]eks[^a-z]"
check "ECR" "container registry|[^a-z]ecr[^a-z]"
check "EC2 Auto Scaling" "auto.?scaling|[^a-z]asg[^a-z]"
check "AWS Batch" "aws batch"
check "Elastic Beanstalk" "beanstalk"
check "Outposts" "outposts"
check "Step Functions" "step function"
check "API Gateway" "api gateway"
check "X-Ray" "x-ray|xray"

echo "=== APPLICATION INTEGRATION ==="
check "SQS" "simple queue|[^a-z]sqs[^a-z]"
check "SNS" "simple notification|[^a-z]sns[^a-z]"
check "EventBridge" "eventbridge"
check "Amazon MQ" "amazon mq|activemq|rabbitmq"
check "AppSync" "appsync"

echo "=== DATABASE ==="
check "RDS" "[^a-z]rds[^a-z]"
check "Aurora" "aurora"
check "Aurora Serverless" "aurora serverless"
check "DynamoDB" "dynamodb"
check "ElastiCache" "elasticache"
check "DocumentDB" "documentdb"
check "Neptune" "neptune"
check "Keyspaces" "keyspaces"
check "QLDB" "qldb|quantum ledger"
check "Redshift" "redshift"
check "RDS Proxy" "rds proxy"

echo "=== STORAGE ==="
check "S3" "[^a-z]s3[^a-z]|simple storage"
check "S3 Glacier" "glacier"
check "EBS" "[^a-z]ebs[^a-z]|elastic block"
check "EFS" "[^a-z]efs[^a-z]|elastic file"
check "FSx" "fsx"
check "Storage Gateway" "storage gateway"
check "AWS Backup" "aws backup"
check "EFS storage classes" "efs lifecycle|one zone-ia"

echo "=== NETWORKING / CDN ==="
check "VPC" "[^a-z]vpc[^a-z]"
check "CloudFront" "cloudfront"
check "Route 53" "route ?53"
check "Global Accelerator" "global accelerator"
check "Direct Connect" "direct connect"
check "Site-to-Site VPN" "site-to-site|s2s vpn"
check "Client VPN" "client vpn"
check "PrivateLink" "privatelink|private link"
check "Transit Gateway" "transit gateway"
check "ELB/ALB/NLB" "load balancer|[^a-z](elb|alb|nlb)[^a-z]"
check "Network Firewall" "network firewall"
check "Shared Services VPC" "shared services vpc"

echo "=== SECURITY / IDENTITY ==="
check "IAM" "[^a-z]iam[^a-z]"
check "IAM Identity Center" "identity center|single sign-on|sso"
check "Cognito" "cognito"
check "KMS" "[^a-z]kms[^a-z]|key management"
check "CloudHSM" "cloudhsm"
check "ACM" "[^a-z]acm[^a-z]|certificate manager"
check "Secrets Manager" "secrets manager"
check "GuardDuty" "guardduty"
check "Macie" "macie"
check "Inspector" "inspector"
check "Shield" "shield"
check "WAF" "[^a-z]waf[^a-z]"
check "Firewall Manager" "firewall manager"
check "Detective" "detective"
check "Security Hub" "security hub"
check "AWS RAM" "resource access manager|[^a-z]ram[^a-z]"
check "Directory Service" "directory service"
check "Organizations/SCP" "organizations|service control polic|[^a-z]scp[^a-z]"
check "Control Tower" "control tower"

echo "=== MANAGEMENT / GOVERNANCE / MIGRATION ==="
check "CloudWatch" "cloudwatch"
check "CloudTrail" "cloudtrail"
check "AWS Config" "aws config|[^a-z]config rule"
check "CloudFormation" "cloudformation"
check "Systems Manager" "systems manager|[^a-z]ssm[^a-z]"
check "Trusted Advisor" "trusted advisor"
check "Compute Optimizer" "compute optimizer"
check "DataSync" "datasync"
check "DMS" "[^a-z]dms[^a-z]|database migration"
check "Snow Family" "snowball|snow family|snowcone"
check "Transfer Family" "transfer family|sftp"
check "Storage Gateway (mig)" "storage gateway"

echo "=== ANALYTICS (lighter weight) ==="
check "Kinesis" "kinesis"
check "Athena" "athena"
check "Glue" "[^a-z]glue[^a-z]"
check "EMR" "[^a-z]emr[^a-z]"
check "Redshift (analytics)" "redshift"
check "QuickSight" "quicksight"
check "Lake Formation" "lake formation"
check "MSK" "[^a-z]msk[^a-z]|managed streaming"
check "OpenSearch" "opensearch|elasticsearch"

echo "=== COST ==="
check "Cost Explorer" "cost explorer"
check "Budgets" "budgets"
check "Savings Plans" "savings plan"
check "Cost and Usage Report" "cost and usage|[^a-z]cur[^a-z]"
